# Generated by Django 4.1.6 on 2023-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=50, verbose_name='Enter Subject Name')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
    ]
